Squashed commit of the following:
commit 898f97bcdc93aaafac2a9bbb20db86755e38dd45
Author: MSP <mario@silvapereira.com>
Date:   Sun Oct 19 12:19:45 2025 +0100

    osxphotos import: improved more progress and total counts indications
     #1960

commit 852d9161d2cd6727c5b6d8cff94ebc04062fc3a8
Merge: 6fecc398 073bc5da
Author: oPromessa <mario@silvapereira.com>
Date:   Thu Oct 16 01:31:53 2025 +0100

    Merge branch 'RhetTbull:main' into oPromessa/issue1960

commit 6fecc3986fe2b555b7c53b5edc1a8858c5685332
Author: MSP <mario@silvapereira.com>
Date:   Wed Oct 15 00:35:43 2025 +0100

    cleanup  test_cli_import

commit 99dd109656df42e8ceac311a18bb87a200f62e2c
Author: MSP <mario@silvapereira.com>
Date:   Wed Oct 15 00:32:15 2025 +0100

    test_cli_import: Added MockTask and adjusted MockProgress in rich_progress.py

    Running test_import.py locally.

    Work in Progress

    One failed test:

    FAILED tests/test_cli_import.py::test_import_auto_live - KeyError: 'not_live.jpeg'

commit 8b6c280e85ef3b91a987b606f65111e3fb60ce20
Author: MSP <mario@silvapereira.com>
Date:   Tue Oct 14 23:59:37 2025 +0100

    osxphotos import: more progress and total counts indications
    Regarding issue #1960

    Changed conftest to run Tests on Monterey with Test-12.0.1 Library

commit b78e58ca2e0aeba60c52e3d1dce952b115dbb274
Merge: 3132f74f 6dbfdf48
Author: oPromessa <mario@silvapereira.com>
Date:   Sun Oct 12 18:46:16 2025 +0100

    Merge branch 'RhetTbull:main' into oPromessa/issue1960

commit 3132f74f020f87d868b4df7c111706bc9119daca
Merge: 97272c12 989640af
Author: oPromessa <mario@silvapereira.com>
Date:   Sat Oct 11 22:29:34 2025 +0100

    Merge branch 'RhetTbull:main' into oPromessa/issue1960

commit 97272c12242d6b780c0d905c4e15077d1143899f
Author: MSP <mario@silvapereira.com>
Date:   Sat Oct 11 22:17:24 2025 +0100

    osxphotos import: more progress and total counts indications
    Addresses #1960